// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJODHmbjdGjEQu7V8I4V0yk314HlDJfX8',
    appId: '1:306275051509:web:5503ac3b0f6c6c29b922bc',
    messagingSenderId: '306275051509',
    projectId: 'fir-login-a26b7',
    authDomain: 'fir-login-a26b7.firebaseapp.com',
    databaseURL: 'https://fir-login-a26b7.firebaseio.com',
    storageBucket: 'fir-login-a26b7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpc-a25vZLueIJlz0aGOvOC-drHVn6888',
    appId: '1:306275051509:android:fd1bf348f484bd12b922bc',
    messagingSenderId: '306275051509',
    projectId: 'fir-login-a26b7',
    databaseURL: 'https://fir-login-a26b7.firebaseio.com',
    storageBucket: 'fir-login-a26b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5lwfjbPobPBxmuOjkhJI_oENZX_0Gxsw',
    appId: '1:306275051509:ios:8ec7cfab192a62fdb922bc',
    messagingSenderId: '306275051509',
    projectId: 'fir-login-a26b7',
    databaseURL: 'https://fir-login-a26b7.firebaseio.com',
    storageBucket: 'fir-login-a26b7.appspot.com',
    androidClientId: '306275051509-7nni1ma1qig0nuqrs7g1ueies8l6qq9o.apps.googleusercontent.com',
    iosClientId: '306275051509-0bkm7vfjm3ta5dv1m0ca77ge8coeb6pk.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5lwfjbPobPBxmuOjkhJI_oENZX_0Gxsw',
    appId: '1:306275051509:ios:14dda0978fb6973bb922bc',
    messagingSenderId: '306275051509',
    projectId: 'fir-login-a26b7',
    databaseURL: 'https://fir-login-a26b7.firebaseio.com',
    storageBucket: 'fir-login-a26b7.appspot.com',
    androidClientId: '306275051509-7nni1ma1qig0nuqrs7g1ueies8l6qq9o.apps.googleusercontent.com',
    iosClientId: '306275051509-e5c70j9pp6a9342aejic4h2ts8n9gv0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
